### PR TITLE
SCRUM-3139: add set/get for subdomain counter(s)

### PR DESCRIPTION
**Pull request by abecerra**

### CODE REVIEW

**Review by oblodgett — COMMENTED** [review]
This is a whole ton extra code then simply adding a set method to the IdentifierResourceRESTInterface

**Comment by abecerra** [comment]
> This is a whole ton extra code then simply adding a set method to the IdentifierResourceRESTInterface

Yes, a bit. I added another information endpoint to get the counters values. This makes easy testing the functionality with swagger.

**Comment by mluypaert** [comment]
@abecerra What's the difference between the GET `/admin/counters` endpoint and the GET '/identifier` endpoint? I thought the identifier endpoint also returned the counter?

**Comment by mluypaert** [comment]
From @abecerra on Slack:
>the first in /admin returns all the counters values

Ok, not really required as everyone should know the classes for which they are responsible and can hence query them individually as and when needed, but sure, then you can have a quick one-glance overview of all classes.

**Review by mluypaert — APPROVED** [review]

**Pull request merged**
